name: Combine Markdown to TXT

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 01:00 UTC
  workflow_dispatch:      # Allows manual triggers from the Actions tab

jobs:
  combine-markdown:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Combine .md files into multiple TXT files
        run: |
          # Initialize variables
          counter=0
          file_index=1
          output_file="BusinessCentralDocumentation_${file_index}.txt"

          # Remove old files (if any)
          rm -f BusinessCentralDocumentation_*.txt

          # Loop over each .md file in the specified directories (no subfolders)
          for folder in business-central \
                        business-central/LocalFunctionality/Germany \
                        business-central/LocalFunctionality/Belgium \
                        business-central/LocalFunctionality/Netherlands
          do
            find "$folder" -maxdepth 1 -type f -name "*.md" | while read -r f
            do
              # Increment counter
              counter=$((counter + 1))

              # Create a new file after every 200 articles
              if [ $((counter % 200)) -eq 1 ] && [ $counter -ne 1 ]; then
                file_index=$((file_index + 1))
                output_file="BusinessCentralDocumentation_${file_index}.txt"
              fi

              # Get the filename (no .md extension)
              filename="$(basename "$f" .md)"

              # Start each article with a link to Microsoft Learn
              echo "Link to Microsoft Learn Page: https://learn.microsoft.com/dynamics365/business-central/$filename" >> "$output_file"

              # Append the file contents
              cat "$f" >> "$output_file"

              # End of article
              echo "end of article" >> "$output_file"

              # Optional blank line for readability
              echo >> "$output_file"
            done
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add BusinessCentralDocumentation_*.txt
          git commit -m "Combine markdown files into multiple TXT files"
          git push || echo "No changes to push"
