name: Split Markdown into Chunks

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 01:00 UTC
  workflow_dispatch:      # Allows manual triggers from the Actions tab

jobs:
  combine-and-split-markdown:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Combine .md files in chunks of 200
        run: |
          # Remove old chunk files (if any) so they don't accumulate
          rm -f BusinessCentralDocumentation_part_*.md
          
          # Variables to track file counts and chunk indexes
          count=0
          file_index=1
          
          # Start with the first output file
          output_file="BusinessCentralDocumentation_part_${file_index}.md"

          # Find only .md files in top-level 'business-central' folder (no subfolders)
          # Sort them alphabetically, then iterate
          find business-central -maxdepth 1 -type f -name "*.md" | sort | while read -r f
          do
            # Extract filename without .md extension
            filename="$(basename "$f" .md)"

            # Write the "Link to Microsoft Learn Page" line
            echo "Link to Microsoft Learn Page: https://learn.microsoft.com/dynamics365/business-central/$filename" >> "$output_file"
            
            # Append the .md file contents
            cat "$f" >> "$output_file"
            
            # Close the article
            echo "end of article" >> "$output_file"

            # Add a blank line for readability (optional)
            echo >> "$output_file"

            # Increment the article counter
            ((count++))

            # If we've reached 200 articles in this chunk, start a new file
            if [ "$count" -eq 200 ]; then
              ((file_index++))
              output_file="BusinessCentralDocumentation_part_${file_index}.md"
              count=0
            fi
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add BusinessCentralDocumentation_part_*.md
          git commit -m "Combine markdown files in chunks of 200"
          git push || echo "No changes to push"
