name: Combine Markdown to TXT

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 01:00 UTC
  workflow_dispatch:      # Allows manual triggers from the Actions tab

jobs:
  combine-markdown:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Combine .md files into BusinessCentralDocumentation.txt
        run: |
          # Remove old file (if any)
          rm -f BusinessCentralDocumentation.txt

          # Loop over each .md file in the top-level business-central folder
          find business-central -maxdepth 1 -type f -name "*.md" | while read -r f
          do
            # Get the filename (no .md extension)
            filename="$(basename "$f" .md)"

            # Start each article with a link to Microsoft Learn
            echo "Link to Microsoft Learn Page: https://learn.microsoft.com/dynamics365/business-central/$filename" >> BusinessCentralDocumentation.txt

            # Append the file contents
            cat "$f" >> BusinessCentralDocumentation.txt

            # End of article
            echo "end of article" >> BusinessCentralDocumentation.txt

            # Optional blank line for readability
            echo >> BusinessCentralDocumentation.txt
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add BusinessCentralDocumentation.txt
          git commit -m "Combine markdown files into BusinessCentralDocumentation.txt"
          git push || echo "No changes to push"
