name: Combine Markdown to TXT

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 01:00 UTC
  workflow_dispatch:      # Allows manual triggers from the Actions tab

jobs:
  combine-markdown:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Combine .md files in top-level business-central folder only
        run: |
          # Remove old .txt file (if any)
          rm -f BusinessCentralDocumentation.txt

          # Find only .md files in "business-central" (excluding subfolders)
          find business-central -maxdepth 1 -type f -name "*.md" \
            -exec cat {} \; >> BusinessCentralDocumentation.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add BusinessCentralDocumentation.txt
          git commit -m "Combine markdown files into .txt" || echo "No changes to commit"
          git push
