name: Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours — adjust as needed
  workflow_dispatch:       # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/MicrosoftDocs/dynamics365smb-docs.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/main into local main
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories --no-edit || true

      - name: Push changes to your fork
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
