name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight (UTC)
  workflow_dispatch: # Allows you to trigger the workflow manually

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout your fork
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          persist-credentials: false # Ensure the credentials are not persisted
          fetch-depth: 0 # Fetch all history for all branches

      # Set up Git
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      # Add the upstream repository
      - name: Add Upstream Repo
        run: git remote add upstream https://github.com/MicrosoftDocs/dynamics365smb-docs.git

      # Fetch changes from the upstream repository
      - name: Fetch Upstream
        run: git fetch upstream

      # Merge changes from upstream/main into fork/main
      - name: Merge Changes
        run: |
          git checkout main
          git merge upstream/main
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main
